### ISSUE TITLE
Макет

### ISSUE THREAD

**Issue by Constantine-P** [mvodev/FSDCourse2#11]
1. По заданию макс ширина 1920, но лучше делать чтобы на 1920+ тоже все выглядело хорошо. То есть растянуть по ширине фоновое изображение, продлить футер и хедер. При этом сам контент оставить где он есть.
![image](https://user-images.githubusercontent.com/18898493/118641677-414ae100-b7fc-11eb-8f34-30d4096039a3.png)

2. Футер должен быть прижат к низу https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.15

3. Здесь должен быть единый календарь, c выбором диапазона:
![image](https://user-images.githubusercontent.com/18898493/118642341-0b5a2c80-b7fd-11eb-83a7-394f840f9511.png)

4. Количество младенцев нужно считать тоже:
![image](https://user-images.githubusercontent.com/18898493/118642764-8b809200-b7fd-11eb-8a0c-9a4ff3ac4631.png)
Пример:
![image](https://user-images.githubusercontent.com/18898493/118642997-d0a4c400-b7fd-11eb-8f8a-de51e199a14c.png)
Сюда нужно запретить писать:
![image](https://user-images.githubusercontent.com/18898493/118645297-8ffa7a00-b800-11eb-9a29-efd403685cbb.png)

5. Здесь кнопка, как будто не относится к инпуту, когда он в фокусе:
![image](https://user-images.githubusercontent.com/18898493/118643304-309b6a80-b7fe-11eb-9d3e-ade4b7a13056.png)

6. Здесь текст явно не вровень с маркером:
![image](https://user-images.githubusercontent.com/18898493/118643619-9f78c380-b7fe-11eb-868e-1ebcfa7f9e8a.png)
В задании есть требование pixelperfect. Просьба проверить, что все совпадет.

7. Не срабатывает если не по сердцу кликать:
![image](https://user-images.githubusercontent.com/18898493/118645508-d64fd900-b800-11eb-9751-1ca2a3e224ac.png)

8. Здесь должен быть слайдер изображений:
![image](https://user-images.githubusercontent.com/18898493/118645668-06977780-b801-11eb-9dfe-effdfe085a95.png)
Примерно такой:
![Peek 2021-05-17 16-14](https://user-images.githubusercontent.com/18898493/118645919-5e35e300-b801-11eb-9d4a-b06f927db98b.gif)

9. Пробелы невпопад
![image](https://user-images.githubusercontent.com/18898493/118646151-a0f7bb00-b801-11eb-9b18-45578b55e037.png)

10. Курсор должен меняться на pointer, когда на ползунок наводим (и на все интерактивные элементы):
![image](https://user-images.githubusercontent.com/18898493/118646408-fd5ada80-b801-11eb-8680-e531d4c74d51.png)

11. Бордер у чекбоксов не по макету
![image](https://user-images.githubusercontent.com/18898493/118646595-3430f080-b802-11eb-8a7d-3cb90fde296e.png)

**Comment by Constantine-P** [comment]
1. Элементы не должны прилипать к границам окна (и друг к другу, при любом разрешении 320 - 1920), фоновое изображение должно растягиваться 
![image](https://user-images.githubusercontent.com/18898493/120081333-f6c04300-c0de-11eb-9388-c3bd2c5982cc.png)

3.
![image](https://user-images.githubusercontent.com/18898493/120081547-fd9b8580-c0df-11eb-9c96-fb941b77a5f5.png)
![image](https://user-images.githubusercontent.com/18898493/120081670-8ca89d80-c0e0-11eb-8a83-538486796723.png)

4. В выпадающем меню есть кнопка "применить", пока она не нажата значения не должны быть применены. Было бы не плохо, если бы все выпадашки закрывались, когда происходит клик где-то вне контрола.

8. 
![image](https://user-images.githubusercontent.com/18898493/120081184-0a1ede80-c0de-11eb-82ba-37209261837f.png)
Слайдеры должны быть на всех карточках номеров. Не хватает анимации, тени и стрелки должны появляться при наведении

**Comment by Constantine-P** [comment]
12. 
![image](https://user-images.githubusercontent.com/18898493/120082035-7865a000-c0e2-11eb-8169-e53b62dad472.png)

**Comment by Constantine-P** [comment]
Пункт 1 не доделал, картика должна растягиваться вниз вслед за горизонтальной линией.
Пункт 4 не сделал
Пункт 5. То, что я обвел (пагинация слайдов, овалы в хроме) не сделал. Тени я имел ввиду те, что на макете подсвечивают стрелки (смотри гифку выше)

**Comment by Constantine-P** [comment]
13. Пробелы:
![image](https://user-images.githubusercontent.com/18898493/121731724-21fd5600-cb13-11eb-8e96-115176eee7bd.png)

14. Label нужно связать с чекбоксом, чтобы, когда кликаем на лейбл, состояние тоже менялось.
![image](https://user-images.githubusercontent.com/18898493/121731813-3c373400-cb13-11eb-9568-21308264d594.png)

15. Ссылки должны куда-то вести (мок-урлы). Выпадающее меню должно выпадать:
![image](https://user-images.githubusercontent.com/18898493/121732166-b667b880-cb13-11eb-8f9d-9924c8cffb6f.png)

16. Какой-то бледный цвет, такой может быть у плейсхолдера, но не у основного. Граница двоится, лучше менять цвет бордера вместо аутлайна.
![image](https://user-images.githubusercontent.com/18898493/121732938-a8666780-cb14-11eb-99a5-dd0681b7c211.png)

17. Картинка выступает:
![image](https://user-images.githubusercontent.com/18898493/121733374-393d4300-cb15-11eb-9ff1-4866fa13d00d.png)

**Comment by Constantine-P** [comment]
16. У плейсхолдеров цвет должен быть как в макете - бледный. У основного текста - ярче. У выбранного радио-баттона цвет текста на макете ярче.
![image](https://user-images.githubusercontent.com/18898493/123505484-2aac6b00-d681-11eb-9c39-93bd8969aca8.png)

18. Понимаю, что в макете/задании не все нюансы показаны/описаны, и само задание не на разработку дизайна. Но все же в реальных проектах такое тоже сплошь и рядом, и мы как-никак разрабатываем интерфейсы. Поэтому выпадающее меню прошу сделать в едином с остальным сайтом стиле. Хорошо бы, чтобы оно закрывалось само, когда кликаем мимо.
![image](https://user-images.githubusercontent.com/18898493/123505583-cb028f80-d681-11eb-85a9-0bb780aa2b23.png)

**Comment by rsilivestr** [comment]
1. В Room details галерея не тянется:
![image](https://user-images.githubusercontent.com/31914503/126313530-48b2bcf4-e4d1-4a76-a59c-714529a7779d.png)

18. Dropdown должен открывается при клике по любому месту инпута, а не тлько по иконке. Также `cursor:pointer` должен применяться ко всему инпуту:
![image](https://user-images.githubusercontent.com/31914503/126310201-9ee5ed3d-1808-49a4-9925-d10ff00a37f4.png)
![image](https://user-images.githubusercontent.com/31914503/126310249-1c2db930-572b-4e30-bd24-9bd67ba675c8.png)

19. Когда гостей `0`, клик на "Применить" должен работать аналогично "Очистить".
![image](https://user-images.githubusercontent.com/31914503/126310750-0c54cff3-3b15-4778-9fa8-1a2d33e43850.png)

20. Выделение в календаре съехало:
![image](https://user-images.githubusercontent.com/31914503/126311112-1ae5b3e6-29ae-44b6-bfe5-e747b0787ad6.png)

21. Кнопка лайка в активном состоянии не соответствует макету:
![image](https://user-images.githubusercontent.com/31914503/126312109-2a9683d8-d7e3-4e48-bfa6-923877bfb2f3.png)

22. Если нажимать на кнопку лайка не посередине - счётчик только увеличивается:
![like](https://user-images.githubusercontent.com/31914503/126312545-fd1acf78-4402-4e1d-9e63-ab39dda29a37.gif)

23. Согласно макету у иконок (комфорт, удобство), звёзд, обводки кнопок градиентная заливка:
![image](https://user-images.githubusercontent.com/31914503/126315789-2dfce472-3d60-47dd-8f6b-d3d422909f9d.png)

24. У отмеченного чекбокса рамка меняет цвет:
![image](https://user-images.githubusercontent.com/31914503/126316713-14c2238e-cee2-470c-8b88-976fccf340af.png)

**Comment by rsilivestr** [comment]
_1. Не исправлено

_18. Исправлено не везде:
![image](https://user-images.githubusercontent.com/31914503/126772902-f30b2a20-cb90-4053-b8c6-63ba71057f0e.png)
![image](https://user-images.githubusercontent.com/31914503/126773077-36a13fb6-2a8e-420c-93d2-7b14f99a3b82.png)

23. В Chrome свойство `background-clip` работает с [префиксом](https://caniuse.com/?search=background-clip). Для автоматизации добавления префиксов есть плагин для PostCSS - [autoprefixer](https://www.npmjs.com/package/autoprefixer).
![image](https://user-images.githubusercontent.com/31914503/126775619-a0e08dfd-fa86-4c1c-bd6c-1649b9fc5573.png)

24. Для _rich checkbox_ то же самое:
![image](https://user-images.githubusercontent.com/31914503/126775820-883f99d0-c9e7-47d4-99f5-ed0cf4853e7f.png)

25. Все интерактивные элементы должны иметь `cursor:pointer`:
![image](https://user-images.githubusercontent.com/31914503/126776470-0b55e88f-f414-4169-8ed3-f9495e51db23.png)

26. Что-то не так с кнопками:
![image](https://user-images.githubusercontent.com/31914503/126776351-147ab114-ae60-496f-a078-3aebd5f90bde.png)

27. В карточке номера должна быть ссылка, для перехода на страницу подробностей (например, в заголовке)
![image](https://user-images.githubusercontent.com/31914503/126778027-8c92e47a-65e9-4d91-b524-efe46e1bfb10.png)

28. Внутренние ссылки сайта не стоит открывать в новом окне (target _blank), также для них необязательно задавать атрибут rel="noopener noreferrer". Это требуется только для внешних ресурсов (например, ссылки социальных сетей).

**Comment by rsilivestr** [comment]
29. Subscription text field - это всё-таки форма, соответственно, иконка (градиентная!) является кнопкой/инпутом для отправки этой формы.
![image](https://user-images.githubusercontent.com/31914503/126779523-528fa387-072d-4abc-be94-711c98b6a759.png)

**Comment by rsilivestr** [comment]
30. В Chrome параграф про "лучшие номера" не на месте:
![image](https://user-images.githubusercontent.com/31914503/126780128-6a3dffb4-d8f8-4c79-b799-71a30d7f780d.png)

**Comment by rsilivestr** [comment]
31. На страницах лэндинга, входа и регистрации футер уехал вниз:
![image](https://user-images.githubusercontent.com/31914503/127108167-97b08b04-0f16-4691-ac0e-124aac71b666.png)

_18. Двойной датапикер открывается только по клику на иконку.
![image](https://user-images.githubusercontent.com/31914503/127108991-086e7385-e3ce-4e5d-a0f8-d413744a66f7.png)

**Comment by rsilivestr** [comment]
32. Курсор не `pointer`, не открывается при клике:
![image](https://user-images.githubusercontent.com/31914503/127667967-fc37da2a-5698-415c-8ef5-52f2f9552974.png)

33. Курсор `pointer` при наведении на пустое пространство.
![image](https://user-images.githubusercontent.com/31914503/127668237-2b53b29a-ce84-479d-80de-8dcdbbb99143.png)

34. Отступы желательно сделать хотя бы примерно одинаковыми (секция с формой слишком близко):
![image](https://user-images.githubusercontent.com/31914503/127671551-6871b7e3-1bbe-439d-b659-f65da611793d.png)

**Comment by rsilivestr** [comment]
Правая кнопка в макете называется Button Hover - состояние кнопки при наведении:
![image](https://user-images.githubusercontent.com/31914503/127825097-debb0383-bea5-4d7c-908e-26b7995d4bab.png)

**Comment by rsilivestr** [comment]
На какую страницу я попаду по клику?)
![image](https://user-images.githubusercontent.com/31914503/127830174-88b22a80-9878-42cd-920e-260b05f0f1fb.png)

**Comment by rsilivestr** [comment]
>На какую страницу я попаду по клику?)

Решение имеет право на жизнь, просто предполагал что-то в таком роде:
![image](https://user-images.githubusercontent.com/31914503/128001964-d4998791-1fe5-4b38-9326-2bad176e2b47.png)

>Правая кнопка в макете называется Button Hover - состояние кнопки при наведении

Я думаю, что к большой кнопке со стрелкой тоже стоит применить.

Кнопка очистить появляется при клике на "минус":
![clearBtn](https://user-images.githubusercontent.com/31914503/128002777-faadb017-b584-4f85-a1f2-f194ada0a3bc.gif)

**Comment by rsilivestr** [comment]
Кнопки в header и кнопки со стрелкой в формах всё ещё не имеют стилей при наведении.

**Comment by rsilivestr** [comment]
На странице регистрации секция с картинкой выше, чем в макете

**Comment by rsilivestr** [comment]
У кнопок в dropdown нет стилей при наведении. И почему-то вместо кнопок там используются `div`-ы:
![image](https://user-images.githubusercontent.com/31914503/129566979-c4810b24-3dda-4726-b704-17f78f7fb802.png)

**Comment by rsilivestr** [comment]
>На странице регистрации секция с картинкой выше, чем в макете

Упс, я перепутал страницы) имел в виду sign-in, там задана `height: 100%` и секция растягивается.

**Comment by rsilivestr** [comment]
Что-то не так с курсором на кнопках формы:
![image](https://user-images.githubusercontent.com/31914503/129907441-c98ebf86-15a6-4efc-b71f-6dab7aa0b433.png)

И с её элементом:
![image](https://user-images.githubusercontent.com/31914503/129907588-468a7327-abe8-4881-9100-b662e5b53231.png)

**Comment by rsilivestr** [comment]
Не всё совпадает с макетом по pixel perfect, шапка хоршо ложится, а контент съезжает:
![image](https://user-images.githubusercontent.com/31914503/129914397-6a32882b-5829-4acd-8425-089901cc0ad6.png)
