### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by Constantine-P** [mvodev/FSDCourse2#14]
https://github.com/fullstack-development/front-end-best-practices/blob/master/Initiation.md#2
Лучше везде делать в два пробела, табы не годятся, в один пробел - тоже.

**Comment by rsilivestr** [comment]
У вложенных блоков в некоторых местах есть лишние отступы:
![image](https://user-images.githubusercontent.com/31914503/128134939-7ec76d63-d275-494c-9b98-da8ac22bc3a3.png)

Помимо отступов хоршо бы поработать над форматированием стилей в целом. Например, в стайл гайде Goolge есть про это [секция](https://google.github.io/styleguide/htmlcssguide.html#CSS_Formatting_Rules).

А чтобы не форматировать всё вручную, можно воспользоваться пакетом [prettier](https://www.npmjs.com/package/prettier). У него и для pug есть плагин.

**Comment by rsilivestr** [comment]
В файлах pug есть места, где вместо 2-х отступов 4 и даже 6:
![image](https://user-images.githubusercontent.com/31914503/128715725-2dc4a848-6b8d-4d3d-a97a-e429224e079a.png)
