### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Constantine-P** [mvodev/FSDCourse2#15]
![image](https://user-images.githubusercontent.com/18898493/123506602-de642980-d686-11eb-8e6c-a98836203cd5.png)
Нужно разделить установку, запуск сервера, сборку. Не нашел команды для старта devserver, только для сборки проекта.

**Comment by rsilivestr** [comment]
Команды лучше оформлять как код (``` или 4 пробела). Ссылку обрезало автоформатом:
![image](https://user-images.githubusercontent.com/31914503/127106885-534a5e82-dc47-4b3f-a11f-1bef0ff78281.png)
