### ISSUE TITLE
Не единообразный нейминг файлов шрифтов

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#26]
![изображение](https://user-images.githubusercontent.com/51095975/140818127-4d05b389-424f-4ec4-9b47-70453ca59e81.png)

Нужно стараться придерживаться единообразия, по дефолту мы предпочитаем использовать нейминг kebab-case и у тебя он используемся по большей мере. 😊

**Comment by mvodev** [comment]
fixed

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/143499829-a9b034a5-71d1-472f-babf-a9f7f01cb1ae.png)

**Comment by mvodev** [comment]
Поменял но git изменения не применил. Удалил добавил измененный.
