### ISSUE TITLE
Не семантичное распределение изображений

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#27]
![изображение](https://user-images.githubusercontent.com/51095975/140818791-ec369247-bb22-4f1e-8c0c-7587195e4ed8.png)

Не ясно какую смысловую нагрузку несет в себе то разделение изображений опираясь на расширение, возможно присмотревшись внимательно ты придумаешь как их грамотно распределить, к тому же не все изображения должны храниться в assets, если изображение строго привязано к кому-то компоненту, то есть смысл положить его в том же компоненте.

**Comment by mvodev** [comment]
Fixed
