### ISSUE TITLE
Фавиконки

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#28]
![изображение](https://user-images.githubusercontent.com/51095975/140819793-5283b36d-0051-4dc1-8c3d-246846bc7fee.png)

В данном файле указанно, что изображения лежат в корне проекта, но в продакшен билде фавиконок в корне нет, пути нужно поправить, это касается и browserconfig.xml. Как я понимаю ты сгенерировал фавиконки на генераторе, он по умолчанию генерирует их так, будто они будут лежать в корне проекта, а если фавиконки некоторые типов лежат в корне проекта их не нужно импортировать, учти это и перепроверь пожалуйста, что подключено, а что нет )

**Comment by mvodev** [comment]
Fixed

**Comment by AkhmadBabaev** [comment]
Ты выбрал довольно не точно решение, в файле browserconfig.xml указываешь favicons/ a в webmanifest ./favicons, возможно и то и то не будет работать, предпочтительнее указать абсолютный путь к фавиконкам /favicons.

**Comment by mvodev** [comment]
fixed
