### ISSUE TITLE
Продакшен сборка

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#29]
В продакшен билде, шрифты лежат и в корне проекта и в assets.

**Comment by AkhmadBabaev** [comment]
Для незамысловатой сборки можно обойтись и динамиечской docs папкой, то есть не хранить её в гите, а чтобы она динамически генерировалась при запуске дев или билд сборки, будет плюсом  если в дев сборке docs папка не будет генерироваться в файловой системе явно, а так же перед каждым запуском дев или прод сборку, можно очистить текущую папку docs если она есть.

**Comment by mvodev** [comment]
Fixed.
