### ISSUE TITLE
Pug 

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#31]
https://github.com/mvodev/FSDCourse2/blob/646de2e321f646e27ad613f3170e5a8b0b52217a/src/index.pug#L3-L13

Тут тоже вопрос к единообразию, кавычки вокруг значений атрибутов отличаются, когда будешь писать на реакте используя синтаксис jsx, можешь по привычке пренебрегать стандартизацией, а затем правило для кавычек тимлид может описать в eslint и вылезет куча предупреждений мелких.

**Comment by mvodev** [comment]
Fixed.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/3659977ad14ac931a5b1186af0a32f3f6c0a5845/src/pages/sign-in-page/sign-in-page.pug#L3-L4

Хоть данный js код лежит внутри pug файла, к нему применяются всё те же требования как обычно. В данном случае интересно почему тут let а не const?

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/3659977ad14ac931a5b1186af0a32f3f6c0a5845/src/pages/headers-and-footers/headers-and-footers.pug#L3-L14

Нужно стремиться упрощать читаемость и взаимодействие с кодом. Сейчас данный компонент выглядит  заграможденым, можно вынести параметры вложенных компонентов за пределы компонента и импортировать. Например это можно сделать с помощью json обьекта. В результате твой код станет лаконичен и когда потребуется обновить вёрстку компонента, придётся меньше скролить и вникать в происходящее, а если нужно добавить новый тип футера или хедера можно будет просто добавить новое поле в нашем объекте с параметрами и считай готово.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/12fe588149e93b1b8c0f8be42624b2ba0cd27454/src/components/list/list.pug#L3-L9

1. Выше я оставлял [правку](https://github.com/mvodev/FSDCourse2/issues/31#issuecomment-979452531), тут тоже самое, таких мест по проекту ещё достаточно, так что нужно пройтись везде и поправить, это касается всех правок.
2. 
```js
let isExpandedList=isExpand===true ? ' bullet-list_is-opened' : '' 
```
isExpand по идее булевая переменная так что лучше написать просто `isExpand ? ...`, имя переменной isExpandedList подразумевает что она хранит булевое значение но это не так.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/12fe588149e93b1b8c0f8be42624b2ba0cd27454/src/components/list/list.pug#L12-L15

Конкатенацию строк выполняем с помощью обратных кавычек ``.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/12fe588149e93b1b8c0f8be42624b2ba0cd27454/src/components/diagram/diagram.pug#L11-L14

Тут должен быть BEM модификатор ключ значение.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/12fe588149e93b1b8c0f8be42624b2ba0cd27454/src/components/list-links/list-links.pug#L2-L5

Во многих случаях можно прописать просто link.isExpandable && 'list-links__link_is-expandable' вместо тернарного оператора, класс со значением false, pug отбросит такой класс.

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/12fe588149e93b1b8c0f8be42624b2ba0cd27454/src/components/social-networks/social-networks.pug#L1-L7

Тут удобнее было бы передавать массив  с нужными значениями, чем сильно привязывать имя социальной сети к компоненту, тем сама можно будет править данные в одном месте - добавить, удалить, поменять местами соц сеть.

**Comment by mvodev** [comment]
fixed
