### ISSUE TITLE
Папка docs поставляется с проектом.

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#32]
Добавить папку docs в .gitignore.

**Comment by mvodev** [comment]
Fixed

**Comment by AkhmadBabaev** [comment]
Почти, сама папка ещё поставляется с проектом так как не была удалена.

**Comment by mvodev** [comment]
Удалил папку docs. Для github pages сделал отдельную ветку. А почему сборка поломанная? Вроде собирает ведь проект?

**Comment by AkhmadBabaev** [comment]
Причину проблемы не исследовал, на момент написания ишью демо страница гитхаб pages была поломана.
