### ISSUE TITLE
Скрипты 

### ISSUE THREAD

**Issue by AkhmadBabaev** [mvodev/FSDCourse2#34]
https://github.com/mvodev/FSDCourse2/blob/3659977ad14ac931a5b1186af0a32f3f6c0a5845/src/pages/ui-kit-page/ui-kit.js#L12-L17

К скриптам такое же требование как и к стилям [тут](https://github.com/mvodev/FSDCourse2/issues/33#issue-1063886820).

**Comment by AkhmadBabaev** [comment]
https://github.com/mvodev/FSDCourse2/blob/3659977ad14ac931a5b1186af0a32f3f6c0a5845/src/components/burger/burger-class.js#L13-L15

Для bind методов предлагаю рассмотреть специальные пакеты которые упрощают эту операцию и улучшают понимание когда метод привязан. Например пакет [autobind-decorator](https://www.npmjs.com/package/autobind-decorator).

**Comment by mvodev** [comment]
fixed
